var annotated_dup =
[
    [ "Board", "class_board.html", "class_board" ],
    [ "Diamond_Board", "class_diamond___board.html", "class_diamond___board" ],
    [ "Diamond_UI", "class_diamond___u_i.html", "class_diamond___u_i" ],
    [ "FiveByFive_Board", "class_five_by_five___board.html", "class_five_by_five___board" ],
    [ "FiveByFive_UI", "class_five_by_five___u_i.html", "class_five_by_five___u_i" ],
    [ "Four_In_A_Row_Board", "class_four___in___a___row___board.html", "class_four___in___a___row___board" ],
    [ "Four_In_A_Row_UI", "class_four___in___a___row___u_i.html", "class_four___in___a___row___u_i" ],
    [ "FourByFour_Board", "class_four_by_four___board.html", "class_four_by_four___board" ],
    [ "FourByFour_UI", "class_four_by_four___u_i.html", "class_four_by_four___u_i" ],
    [ "GameManager", "class_game_manager.html", "class_game_manager" ],
    [ "Infinity_Board", "class_infinity___board.html", "class_infinity___board" ],
    [ "Infinity_UI", "class_infinity___u_i.html", "class_infinity___u_i" ],
    [ "Memory_Board", "class_memory___board.html", "class_memory___board" ],
    [ "Memory_UI", "class_memory___u_i.html", "class_memory___u_i" ],
    [ "Misere_AI_Player", "class_misere___a_i___player.html", "class_misere___a_i___player" ],
    [ "Misere_Board", "class_misere___board.html", "class_misere___board" ],
    [ "Misere_UI", "class_misere___u_i.html", "class_misere___u_i" ],
    [ "Move", "class_move.html", "class_move" ],
    [ "Numerical_TicTacToe_Board", "class_numerical___tic_tac_toe___board.html", "class_numerical___tic_tac_toe___board" ],
    [ "Numerical_TicTacToe_UI", "class_numerical___tic_tac_toe___u_i.html", "class_numerical___tic_tac_toe___u_i" ],
    [ "Obstacles_Board", "class_obstacles___board.html", "class_obstacles___board" ],
    [ "Obstacles_UI", "class_obstacles___u_i.html", "class_obstacles___u_i" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "Pyramid_XO_Board", "class_pyramid___x_o___board.html", "class_pyramid___x_o___board" ],
    [ "Pyramid_XO_UI", "class_pyramid___x_o___u_i.html", "class_pyramid___x_o___u_i" ],
    [ "SUS_Board", "class_s_u_s___board.html", "class_s_u_s___board" ],
    [ "SUS_UI", "class_s_u_s___u_i.html", "class_s_u_s___u_i" ],
    [ "UI", "class_u_i.html", "class_u_i" ],
    [ "Ultimate_Board", "class_ultimate___board.html", "class_ultimate___board" ],
    [ "Ultimate_Move", "class_ultimate___move.html", "class_ultimate___move" ],
    [ "Ultimate_UI", "class_ultimate___u_i.html", "class_ultimate___u_i" ],
    [ "Word_Board", "class_word___board.html", "class_word___board" ],
    [ "Word_UI", "class_word___u_i.html", "class_word___u_i" ],
    [ "X_O_Board", "class_x___o___board.html", "class_x___o___board" ],
    [ "XO_UI", "class_x_o___u_i.html", "class_x_o___u_i" ]
];