var files_dup =
[
    [ "BoardGame_Classes.h", "_board_game___classes_8h.html", "_board_game___classes_8h" ],
    [ "Diamond_TicTacToe.cpp", "_diamond___tic_tac_toe_8cpp.html", null ],
    [ "Diamond_TicTacToe.h", "_diamond___tic_tac_toe_8h.html", "_diamond___tic_tac_toe_8h" ],
    [ "FiveByFive_Classes.cpp", "_five_by_five___classes_8cpp.html", null ],
    [ "FiveByFive_Classes.h", "_five_by_five___classes_8h.html", "_five_by_five___classes_8h" ],
    [ "Four_In_A_Row_UI.cpp", "_four___in___a___row___u_i_8cpp.html", null ],
    [ "Four_In_A_Row_UI.h", "_four___in___a___row___u_i_8h.html", "_four___in___a___row___u_i_8h" ],
    [ "FourByFour_Classes.cpp", "_four_by_four___classes_8cpp.html", null ],
    [ "FourByFour_Classes.h", "_four_by_four___classes_8h.html", "_four_by_four___classes_8h" ],
    [ "Infinity_TicTacToe.cpp", "_infinity___tic_tac_toe_8cpp.html", null ],
    [ "Infinity_TicTacToe.h", "_infinity___tic_tac_toe_8h.html", "_infinity___tic_tac_toe_8h" ],
    [ "Memory_TicTacToe.cpp", "_memory___tic_tac_toe_8cpp.html", null ],
    [ "Memory_TicTacToe.h", "_memory___tic_tac_toe_8h.html", "_memory___tic_tac_toe_8h" ],
    [ "Misere.cpp", "_misere_8cpp.html", null ],
    [ "Misere.h", "_misere_8h.html", "_misere_8h" ],
    [ "Numerical_TicTacToe.cpp", "_numerical___tic_tac_toe_8cpp.html", null ],
    [ "Numerical_TicTacToe.h", "_numerical___tic_tac_toe_8h.html", "_numerical___tic_tac_toe_8h" ],
    [ "Obstacles_Classes.cpp", "_obstacles___classes_8cpp.html", null ],
    [ "Obstacles_Classes.h", "_obstacles___classes_8h.html", "_obstacles___classes_8h" ],
    [ "Pyramid_TicTacToe.cpp", "_pyramid___tic_tac_toe_8cpp.html", null ],
    [ "Pyramid_TicTacToe.h", "_pyramid___tic_tac_toe_8h.html", "_pyramid___tic_tac_toe_8h" ],
    [ "sus_classes.cpp", "sus__classes_8cpp.html", "sus__classes_8cpp" ],
    [ "sus_classes.h", "sus__classes_8h.html", "sus__classes_8h" ],
    [ "Ultimate_TicTacToe_Classes.cpp", "_ultimate___tic_tac_toe___classes_8cpp.html", null ],
    [ "Ultimate_TicTacToe_Classes.h", "_ultimate___tic_tac_toe___classes_8h.html", "_ultimate___tic_tac_toe___classes_8h" ],
    [ "Word_TicTacToe.cpp", "_word___tic_tac_toe_8cpp.html", null ],
    [ "Word_TicTacToe.h", "_word___tic_tac_toe_8h.html", "_word___tic_tac_toe_8h" ],
    [ "XO_Classes.cpp", "_x_o___classes_8cpp.html", null ],
    [ "XO_Classes.h", "_x_o___classes_8h.html", "_x_o___classes_8h" ],
    [ "XO_Demo.cpp", "_x_o___demo_8cpp.html", "_x_o___demo_8cpp" ]
];